config/routes.rb
Rails.application.routes.draw do
  resources :subscribes
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :members
  resources :subscribes
  resources :categories
  resources :feeds
  resources :users

  root 'home#index'

  get 'home/list' => 'home#list'
  get '/display' => 'home#display'
  get '/add' => 'home#add'
  get '/delete' => 'home#delete'
  get '/addFavorite' => 'home#addFavorite'
  get '/removeFavorite' => 'home#removeFavorite'
  get 'home/logout' => "home#logout"
  get 'members/sign_up' => 'members#sign_up'
  post 'registration/delete' => 'registration#delete'
  get 'list' => 'home#list'

end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  before_action :set_subscribe, only: [:show, :edit, :update, :destroy]

  # GET /subscribes
  # GET /subscribes.json
  def index
    @subscribes = Subscribe.all
  end

  # GET /subscribes/1
  # GET /subscribes/1.json
  def show
  end

  # GET /subscribes/new
  def new
    @subscribe = Subscribe.new
  end

  # GET /subscribes/1/edit
  def edit
  end

  # POST /subscribes
  # POST /subscribes.json
  def create
    @subscribe = Subscribe.new(subscribe_params)

    respond_to do |format|
      if @subscribe.save
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully created.' }
        format.json { render :show, status: :created, location: @subscribe }
      else
        format.html { render :new }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribes/1
  # PATCH/PUT /subscribes/1.json
  def update
    respond_to do |format|
      if @subscribe.update(subscribe_params)
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscribe }
      else
        format.html { render :edit }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribes/1
  # DELETE /subscribes/1.json
  def destroy
    @subscribe.destroy
    respond_to do |format|
      format.html { redirect_to subscribes_url, notice: 'Subscribe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe
      @subscribe = Subscribe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscribe_params
      params.require(:subscribe).permit(:user_id, :feed_id)
    end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_form.html.erb
<%= form_for(@subscribe) do |f| %>
  <% if @subscribe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscribe.errors.count, "error") %> prohibited this subscribe from being saved:</h2>

      <ul>
      <% @subscribe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :feed_id %><br>
    <%= f.number_field :feed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribes/edit.html.erb
<h1>Editing Subscribe</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscribe %> |
<%= link_to 'Back', subscribes_path %>

app/views/subscribes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscribes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Feed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribes.each do |subscribe| %>
      <tr>
        <td><%= subscribe.user_id %></td>
        <td><%= subscribe.feed_id %></td>
        <td><%= link_to 'Show', subscribe %></td>
        <td><%= link_to 'Edit', edit_subscribe_path(subscribe) %></td>
        <td><%= link_to 'Destroy', subscribe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscribe', new_subscribe_path %>

app/views/subscribes/new.html.erb
<h1>New Subscribe</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribes_path %>

app/views/subscribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscribe.user_id %>
</p>

<p>
  <strong>Feed:</strong>
  <%= @subscribe.feed_id %>
</p>

<%= link_to 'Edit', edit_subscribe_path(@subscribe) %> |
<%= link_to 'Back', subscribes_path %>